
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beachwood-high-school.github.io" #for sitemap

# Google-analytics
google-analytics:
  id: ""
sass:
  sass_dir: assets/_sass

picture:
  nomarkdown: false


exclude: ["package.json", "src", "node_modules", "vendor/bundle"]


##development options
host: 192.168.0.199 #make it your own ip address to be able to test from mobile devices in the LAN
livereload: true

plugins:
  - jekyll-sitemap